// Operator's Signal Room: account settings make the mobile-to-panel connection explicit instead of hiding integration state.
import { Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import { useEffect, useState } from "react";
import { router } from "expo-router";
import * as Haptics from "expo-haptics";

import { AppIcon } from "@/components/app-icon";
import { Screen } from "@/components/screen";
import { useRoyalApp } from "@/lib/app-state";

export default function AccountScreen() {
  const { panelUrl, setPanelUrl, refresh, loading, bootstrap, role } = useRoyalApp();
  const [draft, setDraft] = useState(panelUrl);
  useEffect(() => setDraft(panelUrl), [panelUrl]);
  const connect = async () => { setPanelUrl(draft); await Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light); await refresh(draft); };
  return <Screen><View style={styles.content}><Text style={styles.eyebrow}>CONNECTION & ROLE</Text><Text style={styles.title}>Account</Text><Text style={styles.subtitle}>Connect the app to the live Royal panel when the mobile API is enabled.</Text><View style={styles.profile}><View style={styles.avatar}><AppIcon name={role === "admin" ? "shield-crown-outline" : "account-outline"} color="#FFFFFF" size={27} /></View><View style={{ flex: 1 }}><Text style={styles.profileTitle}>{bootstrap?.user.username ?? "Panel not connected"}</Text><Text style={styles.profileMeta}>{role === "admin" ? "Administrator workspace" : "Customer workspace"}</Text></View><Pressable onPress={() => router.push("/role")} style={({ pressed }) => [styles.switch, pressed && styles.pressed]}><Text style={styles.switchText}>Switch</Text></Pressable></View><View style={styles.form}><Text style={styles.label}>Live panel URL</Text><TextInput value={draft} onChangeText={setDraft} autoCapitalize="none" keyboardType="url" placeholder="https://your-royal-panel.example" placeholderTextColor="#9BA0B6" style={styles.input} returnKeyType="done" onSubmitEditing={connect} /><Text style={styles.helper}>The native app expects an authenticated `/api/mobile/bootstrap` endpoint at this address.</Text><Pressable onPress={connect} disabled={loading} style={({ pressed }) => [styles.primary, (pressed || loading) && styles.pressed]}><AppIcon name="link-variant" color="#FFFFFF" size={19} /><Text style={styles.primaryText}>{loading ? "Connecting…" : "Connect live panel"}</Text></Pressable></View><View style={styles.note}><AppIcon name="shield-check-outline" color="#6C5CE7" size={22} /><View style={{ flex: 1 }}><Text style={styles.noteTitle}>No credentials are stored in the UI</Text><Text style={styles.noteText}>A full native deployment should use an authenticated token exchange over HTTPS rather than a web-view session.</Text></View></View></View></Screen>;
}

const styles = StyleSheet.create({ content: { flex: 1, padding: 20, gap: 18 }, eyebrow: { color: "#6C5CE7", fontSize: 11, letterSpacing: 1.2, fontWeight: "900" }, title: { marginTop: -14, color: "#252A4D", fontSize: 28, fontWeight: "800" }, subtitle: { marginTop: -12, color: "#737A95", fontSize: 13, lineHeight: 19 }, profile: { flexDirection: "row", alignItems: "center", gap: 12, padding: 15, borderRadius: 20, backgroundColor: "#27244D" }, avatar: { width: 48, height: 48, borderRadius: 16, alignItems: "center", justifyContent: "center", backgroundColor: "#6C5CE7" }, profileTitle: { color: "#FFFFFF", fontSize: 15, fontWeight: "800" }, profileMeta: { marginTop: 3, color: "#D5D2F2", fontSize: 12 }, switch: { paddingHorizontal: 10, paddingVertical: 7, borderRadius: 10, backgroundColor: "#3A3768" }, switchText: { color: "#FFFFFF", fontSize: 11, fontWeight: "800" }, form: { padding: 16, borderRadius: 20, borderWidth: 1, borderColor: "#E4E7F1", backgroundColor: "#FFFFFF" }, label: { color: "#434A70", fontSize: 13, fontWeight: "800" }, input: { marginTop: 9, borderWidth: 1, borderColor: "#DDE0ED", borderRadius: 13, paddingHorizontal: 12, paddingVertical: 12, color: "#272D50", fontSize: 13, backgroundColor: "#FBFBFE" }, helper: { marginTop: 8, color: "#838AA3", fontSize: 11, lineHeight: 16 }, primary: { flexDirection: "row", justifyContent: "center", alignItems: "center", gap: 8, marginTop: 15, borderRadius: 13, paddingVertical: 13, backgroundColor: "#6C5CE7" }, primaryText: { color: "#FFFFFF", fontSize: 13, fontWeight: "800" }, note: { flexDirection: "row", gap: 10, padding: 15, borderRadius: 18, backgroundColor: "#F0EEFF" }, noteTitle: { color: "#4C427E", fontSize: 12, fontWeight: "800" }, noteText: { marginTop: 4, color: "#726A9C", fontSize: 11, lineHeight: 16 }, pressed: { opacity: 0.78, transform: [{ scale: 0.97 }] } });
