// Operator's Signal Room: a role-aware native home surfaces the next operational move before any secondary detail.
import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { router } from "expo-router";
import * as Haptics from "expo-haptics";

import { AppIcon } from "@/components/app-icon";
import { NotificationRow } from "@/components/notification-row";
import { Screen } from "@/components/screen";
import { useRoyalApp } from "@/lib/app-state";

export default function HomeScreen() {
  const { role, bootstrap, panelUrl, refresh, loading, error } = useRoyalApp();
  const isAdmin = role === "admin";
  const notifications = bootstrap?.notifications.slice(0, 3) ?? [];
  const connect = async () => { await Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light); await refresh(); };
  return <Screen><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}>
    <View style={styles.topline}><View><Text style={styles.eyebrow}>{isAdmin ? "ADMIN SIGNAL ROOM" : "ROYAL SMM MOBILE"}</Text><Text style={styles.title}>{isAdmin ? "Operations, in focus." : "Your service desk."}</Text></View><Pressable onPress={() => router.push("/role")} style={({ pressed }) => [styles.role, pressed && styles.pressed]}><AppIcon name={isAdmin ? "shield-crown-outline" : "account-outline"} size={18} /><Text style={styles.roleText}>{isAdmin ? "Admin" : "Customer"}</Text></Pressable></View>
    <View style={styles.hero}><View style={styles.heroSignal}><View style={styles.signalDot} /><View style={styles.signalLine} /><View style={[styles.signalDot, styles.signalDotMid]} /><View style={styles.signalLine} /><View style={[styles.signalDot, styles.signalDotTop]} /></View><Text style={styles.heroKicker}>{isAdmin ? "ROLE-AWARE OPERATIONS" : "ACCOUNT-FIRST SERVICE DELIVERY"}</Text><Text style={styles.heroTitle}>{isAdmin ? "Review delivery signals before they become noise." : "Track every service signal in one calm workspace."}</Text><Text style={styles.heroText}>{bootstrap ? "Your live panel is connected." : "Connect your panel to load live orders and notifications."}</Text><Pressable onPress={connect} disabled={loading} style={({ pressed }) => [styles.heroButton, (pressed || loading) && styles.pressed]}><Text style={styles.heroButtonText}>{loading ? "Connecting…" : bootstrap ? "Refresh live data" : "Connect live panel"}</Text><AppIcon name="arrow-right" color="#FFFFFF" size={18} /></Pressable></View>
    {!bootstrap && <View style={styles.connection}><View style={styles.connectionIcon}><AppIcon name="link-variant" color="#6C5CE7" /></View><View style={styles.connectionCopy}><Text style={styles.connectionTitle}>{panelUrl ? "Native API required" : "Add your panel URL"}</Text><Text style={styles.connectionText}>{error ?? "Open Account, add the HTTPS address of the Royal panel, then connect when the mobile API is enabled."}</Text></View></View>}
    <View style={styles.sectionHead}><View><Text style={styles.sectionTitle}>{isAdmin ? "Control routes" : "Quick routes"}</Text><Text style={styles.sectionMeta}>{isAdmin ? "Role-aware operations" : "Customer essentials"}</Text></View></View><View style={styles.actionGrid}><ActionCard icon={isAdmin ? "bell-badge-outline" : "cart-plus"} label={isAdmin ? "Review signals" : "Start an order"} note={isAdmin ? "Reach customer context" : "Open the delivery queue"} onPress={() => router.push("/(tabs)/notifications")} /><ActionCard icon={isAdmin ? "account-group-outline" : "wallet-outline"} label={isAdmin ? "Manage accounts" : "Add funds"} note={isAdmin ? "Customer access stays server controlled" : "Open connection settings"} onPress={() => router.push("/(tabs)/account")} /></View>
    <View style={styles.sectionHead}><View><Text style={styles.sectionTitle}>Recent signals</Text><Text style={styles.sectionMeta}>{bootstrap ? `${bootstrap.unreadNotificationCount} unread` : "Inbox becomes live after connection"}</Text></View><Pressable onPress={() => router.push("/(tabs)/notifications")}><Text style={styles.viewAll}>View inbox</Text></Pressable></View><View style={styles.signalPanel}>{notifications.length ? notifications.map((item) => <NotificationRow key={item.id} item={item} />) : <View style={styles.empty}><AppIcon name="bell-sleep-outline" color="#8D93AA" size={25} /><Text style={styles.emptyTitle}>No live signals loaded</Text><Text style={styles.emptyText}>Your customer or admin inbox will appear here after the API connects.</Text></View>}</View>
  </ScrollView></Screen>;
}

function ActionCard({ icon, label, note, onPress }: { icon: Parameters<typeof AppIcon>[0]["name"]; label: string; note: string; onPress: () => void }) {
  return <Pressable onPress={onPress} style={({ pressed }) => [styles.action, pressed && styles.pressed]}><View style={styles.actionIcon}><AppIcon name={icon} /></View><Text style={styles.actionLabel}>{label}</Text><Text style={styles.actionNote}>{note}</Text><AppIcon name="arrow-top-right" color="#7B739F" size={16} /></Pressable>;
}

const styles = StyleSheet.create({
  content: { padding: 20, paddingBottom: 34, gap: 22 }, topline: { flexDirection: "row", justifyContent: "space-between", alignItems: "flex-start" }, eyebrow: { color: "#6C5CE7", fontSize: 11, letterSpacing: 1.2, fontWeight: "900" }, title: { marginTop: 4, color: "#20254A", fontSize: 27, lineHeight: 33, fontWeight: "800" }, role: { flexDirection: "row", alignItems: "center", gap: 5, paddingHorizontal: 11, paddingVertical: 8, borderRadius: 999, backgroundColor: "#EEEBFF" }, roleText: { color: "#5E4FD0", fontSize: 12, fontWeight: "800" },
  hero: { minHeight: 224, overflow: "hidden", borderRadius: 24, padding: 20, backgroundColor: "#28254F", justifyContent: "flex-end" }, heroSignal: { position: "absolute", right: 28, top: 23, alignItems: "center" }, signalDot: { width: 12, height: 12, borderRadius: 6, backgroundColor: "#FFB547", shadowColor: "#FFB547", shadowOpacity: .7, shadowRadius: 8 }, signalDotMid: { backgroundColor: "#8D82F5" }, signalDotTop: { backgroundColor: "#FFFFFF" }, signalLine: { width: 2, height: 27, backgroundColor: "#645CB3" }, heroKicker: { color: "#BBB5F4", fontSize: 10, letterSpacing: 1.1, fontWeight: "900" }, heroTitle: { maxWidth: 285, marginTop: 7, color: "#FFFFFF", fontSize: 21, lineHeight: 27, fontWeight: "800" }, heroText: { maxWidth: 265, marginTop: 7, color: "#E2E1F8", fontSize: 13, lineHeight: 18 }, heroButton: { alignSelf: "flex-start", flexDirection: "row", alignItems: "center", gap: 7, marginTop: 16, borderRadius: 12, paddingHorizontal: 13, paddingVertical: 10, backgroundColor: "#6C5CE7" }, heroButtonText: { color: "#FFFFFF", fontSize: 12, fontWeight: "800" },
  connection: { flexDirection: "row", gap: 11, padding: 14, borderRadius: 17, borderWidth: 1, borderColor: "#E3E0FB", backgroundColor: "#FCFBFF" }, connectionIcon: { width: 36, height: 36, borderRadius: 13, backgroundColor: "#EEEBFF", alignItems: "center", justifyContent: "center" }, connectionCopy: { flex: 1 }, connectionTitle: { color: "#39325C", fontSize: 13, fontWeight: "800" }, connectionText: { marginTop: 3, color: "#737994", fontSize: 12, lineHeight: 17 },
  sectionHead: { flexDirection: "row", alignItems: "flex-end", justifyContent: "space-between", marginTop: 2 }, sectionTitle: { color: "#252A4D", fontSize: 17, fontWeight: "800" }, sectionMeta: { marginTop: 2, color: "#8A90AA", fontSize: 11, fontWeight: "600" }, viewAll: { color: "#6554D6", fontSize: 12, fontWeight: "800" }, actionGrid: { flexDirection: "row", gap: 12 }, action: { flex: 1, minHeight: 148, padding: 14, borderRadius: 20, borderWidth: 1, borderColor: "#E6E8F2", backgroundColor: "#FFFFFF" }, actionIcon: { alignSelf: "flex-start", marginBottom: 14, width: 36, height: 36, borderRadius: 13, alignItems: "center", justifyContent: "center", backgroundColor: "#F0EEFF" }, actionLabel: { color: "#33395D", fontSize: 13, fontWeight: "800" }, actionNote: { flex: 1, marginTop: 4, color: "#7D849E", fontSize: 11, lineHeight: 15 }, signalPanel: { paddingHorizontal: 14, borderRadius: 20, borderWidth: 1, borderColor: "#E6E8F2", backgroundColor: "#FFFFFF" }, empty: { alignItems: "center", paddingVertical: 30, paddingHorizontal: 18 }, emptyTitle: { marginTop: 8, color: "#454C70", fontSize: 14, fontWeight: "800" }, emptyText: { marginTop: 4, color: "#8087A0", fontSize: 12, textAlign: "center", lineHeight: 17 }, pressed: { opacity: 0.82, transform: [{ scale: 0.97 }] },
});
